version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tienda_online_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app:/app/app

  redis:
    image: "redis:7-alpine"
    container_name: tienda_online_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: